export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const PROJECT_REQUEST = 'PROJECT_REQUEST'
export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST'
export const PROJECT_DELETE = 'PROJECT_DELETE'
export const PROJECT_DELETE_FAILED = 'PROJECT_DELETE_FAILED'